### ISSUE TITLE
Would you like to tell us how to use it?

### ISSUE THREAD

**Issue by wlmnzf** [omeranson/nextce4nusmv#1]
Would you like to tell us how to use it? I try the nextce4nusmv to run test/NCEEx.smv, but it seems that  the result is the same with the origin version, and I do not find the next counterexample.

**Comment by omeranson** [comment]
I added some documentation, but it doesn't look like it works. I fear the project may be full of bugs that have to be found and fixed. Sorry about that.

**Comment by omeranson** [comment]
Just to update - Seems to work with test files `nusmv/test/1.smv` and `2.smv`.

**Comment by wlmnzf** [comment]
Thanks very much, it helps me a lot.
